// Generated by CoffeeScript 1.10.0
(function() {
  var callBackFormOpen, enableCallBackForm, enableContactForm, enableOrderForm, enableReviewForm, iSendAJAX, mobileNav;

  mobileNav = function() {
    $('#mobile_nav_toggle').on('click', '', function() {
      return $('#mobile_nav_toggle, #mobile_nav').toggleClass('is_open');
    });
  };

  callBackFormOpen = function() {
    $('.call_back_form__toggle').on('click', '', function() {
      return $('.call_back_form__toggle, .call_back_form__wrap').toggleClass('is_open');
    });
  };

  enableCallBackForm = function() {
    var TheForm, sendForm;
    TheForm = document.getElementById('call_back_form');
    if (TheForm) {
      sendForm = document.getElementById('call_back_form__button');
      TheForm.addEventListener('submit', function(event) {
        return iSendAJAX(event, TheForm, sendForm);
      });
    } else {

    }
  };

  enableContactForm = function() {
    var TheForm, sendForm;
    TheForm = document.getElementById('contact_form');
    if (TheForm) {
      sendForm = document.getElementById('contact_form__button');
      TheForm.addEventListener('submit', function(event) {
        return iSendAJAX(event, TheForm, sendForm);
      });
    } else {

    }
  };

  enableReviewForm = function() {
    var TheForm, sendForm;
    TheForm = document.getElementById('review_form');
    if (TheForm) {
      sendForm = document.getElementById('review_form__button');
      TheForm.addEventListener('submit', function(event) {
        return iSendAJAX(event, TheForm, sendForm);
      });
    } else {

    }
  };

  enableOrderForm = function() {
    var TheForm, sendForm;
    TheForm = document.getElementById('order_form');
    if (TheForm) {
      sendForm = document.getElementById('order_form__button');
      TheForm.addEventListener('submit', function(event) {
        return iSendAJAX(event, TheForm, sendForm);
      });
    } else {

    }
  };

  iSendAJAX = function(event, form, sendButton) {
    var formData, message, request;
    event.preventDefault();
    message = {};
    message.loading = 'Отправка...';
    message.success = 'Форма успешно отправлена! Мы свяжемся с Вами в ближайшее время.';
    message.failure = 'Возникла ошибка при отправке.';
    request = new XMLHttpRequest;
    request.open('POST', '//formspree.io/n.anisimov.23@gmail.com', true);
    request.setRequestHeader('accept', 'application/json');
    formData = new FormData(form);
    request.send(formData);
    return request.onreadystatechange = function() {
      if (request.readyState < 4) {
        sendButton.innerHTML = message.loading;
        sendButton.className = 'form__button--loading';
      } else if (request.readyState === 4) {
        if (request.status === 200 && request.status < 300) {
          sendButton.innerHTML = message.success;
          sendButton.className = 'form__button--success';
        } else {
          form.insertAdjacentHTML('beforeend', message.failure);
        }
      }
    };
  };

  $(function() {
    mobileNav();
    callBackFormOpen();
    enableCallBackForm();
    enableContactForm();
    enableReviewForm();
    enableOrderForm();
  });

}).call(this);
