// Generated by CoffeeScript 1.10.0
(function() {
  var callBackFormModalClose, callBackFormModalOpen, enableCallBackForm, enableContactForm, enableOrderForm, enableQuestionForm, enableReviewForm, iSendAJAX, ifExistsEnableContactForm, ifExistsEnableOrderForm, ifExistsEnableReviewForm, mobileNav, questionFormModalClose, questionFormModalOpen, smoothScroll;

  questionFormModalOpen = function() {
    $('#question_form_opener').on('click', function() {
      return $('#question_modal').addClass('is_open');
    });
  };

  questionFormModalClose = function() {
    $('#question_modal__close').on('click', function() {
      return $('#question_modal').removeClass('is_open');
    });
  };

  callBackFormModalOpen = function() {
    $('#call_back_form_opener').on('click', function() {
      return $('#call_back_modal').addClass('is_open');
    });
  };

  callBackFormModalClose = function() {
    $('#call_back_modal__close').on('click', function() {
      return $('#call_back_modal').removeClass('is_open');
    });
  };

  mobileNav = function() {
    $('#mobile_nav_toggle').on('click', '', function() {
      return $('#mobile_nav_toggle, #mobile_nav').toggleClass('is_open');
    });
  };

  smoothScroll = function(duration) {
    $('a[href^="#"]').on('click', function(event) {
      var target;
      target = $($(this).attr('href'));
      if (target.length) {
        event.preventDefault();
        $('html, body').animate({
          scrollTop: target.offset().top
        }, duration);
      }
    });
  };

  enableCallBackForm = function() {
    var TheForm, sendForm;
    TheForm = document.getElementById('call_back_form');
    sendForm = document.getElementById('call_back_form__button');
    TheForm.addEventListener('submit', function(event) {
      iSendAJAX(event, TheForm, sendForm);
    });
  };

  enableQuestionForm = function() {
    var TheForm, sendForm;
    TheForm = document.getElementById('question_form');
    sendForm = document.getElementById('question_form__button');
    TheForm.addEventListener('submit', function(event) {
      iSendAJAX(event, TheForm, sendForm);
    });
  };

  enableContactForm = function() {
    var TheForm, sendForm;
    TheForm = document.getElementById('contact_form');
    sendForm = document.getElementById('contact_form__button');
    TheForm.addEventListener('submit', function(event) {
      iSendAJAX(event, TheForm, sendForm);
    });
  };

  enableReviewForm = function() {
    var TheForm, sendForm;
    TheForm = document.getElementById('review_form');
    sendForm = document.getElementById('review_form__button');
    TheForm.addEventListener('submit', function(event) {
      iSendAJAX(event, TheForm, sendForm);
    });
  };

  enableOrderForm = function() {
    var TheForm, sendForm;
    TheForm = document.getElementById('order_form');
    sendForm = document.getElementById('order_form__button');
    TheForm.addEventListener('submit', function(event) {
      iSendAJAX(event, TheForm, sendForm);
    });
  };

  ifExistsEnableContactForm = function() {
    if ($('#contact_form').length > 0) {
      return enableContactForm();
    }
  };

  ifExistsEnableReviewForm = function() {
    if ($('#review_form').length > 0) {
      return enableReviewForm();
    }
  };

  ifExistsEnableOrderForm = function() {
    if ($('#ordert_form').length > 0) {
      return enableOrderForm();
    }
  };

  iSendAJAX = function(event, form, sendButton) {
    var formData, message, request;
    event.preventDefault();
    message = {};
    message.loading = 'Отправка...';
    message.success = 'Спасибо! Мы свяжемся с Вами в ближайшее время.';
    message.failure = 'Whoops! There was a problem sending your message.';
    request = new XMLHttpRequest;
    request.open('POST', '//formspree.io/n.anisimov.23@gmail.com', true);
    request.setRequestHeader('accept', 'application/json');
    formData = new FormData(form);
    request.send(formData);
    request.onreadystatechange = function() {
      if (request.readyState < 4) {
        sendButton.innerHTML = message.loading;
        sendButton.className = 'form-control btn btnFormLoad';
      } else if (request.readyState === 4) {
        if (request.status === 200 && request.status < 300) {
          sendButton.innerHTML = message.success;
          sendButton.className = 'form-control btn btnFormSent';
        } else {
          form.insertAdjacentHTML('beforeend', message.failure);
        }
      }
    };
  };

  $(function() {
    mobileNav();
    callBackFormModalOpen();
    callBackFormModalClose();
    questionFormModalOpen();
    questionFormModalClose();
    enableCallBackForm();
    enableQuestionForm();
    ifExistsEnableContactForm();
    ifExistsEnableReviewForm();
    ifExistsEnableOrderForm();
  });

}).call(this);
