title: Turoboz
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: localhost:3000/
email: TODO@turobozperm.ru
vk_group: vk.com/club33948424
company_legal: Новикова Н.В.
copyright_dates: 2013-2016

github_username:  none23

# Build settings
markdown: kramdown

# Custom settings
exclude: ["node_modules",
          "gulpfile.js",
          "gulpfile.coffee",
          "package.json",
          "README.md"]
collections:
 - tours
 - testimonials
 - news
 - tags
