title: Туробоз
description: > 
    Turoboz website
url: https://turoboz.com
email: TODO@TODO.TODO
vk_group: vk.com/club33948424
company_legal: TODO
copyright_dates: 2013-2016

github_username:  none23

# Build settings
markdown: kramdown

# Custom settings
exclude: ["node_modules",
          ".board",
          "board",
          "gh-pages",
          "Gemfile",
          "Gemfile.lock",
          "gulpfile.js",
          "gulpfile.coffee",
          "package.json",
          "README.md"]
collections:
  tours:
    output: true
  news:
    output: true
