title: Туробоз
description: > 
    Turoboz website
url: https://www.turoboz.com
unsafe_url: http://www.turoboz.com
email: info@turoboz.com
vk_group: vk.com/club33948424
company_legal:  Туробоз
copyright_dates: 2013-2016

github_username:  none23
google_analytics: UA-83021795-1
# Build settings
markdown: kramdown

# Custom settings
exclude: ["node_modules",
          ".board",
          "board",
          "gh-pages",
          "Gemfile",
          "Gemfile.lock",
          "gulpfile.js",
          "gulpfile.coffee",
          "package.json",
          "README.md",
          "webpack.config.js"]
collections:
  tours:
    output: true
  news:
    output: true
gems:
  - jekyll-sitemap
