title: ТурОбоз - Экскурсии по Перми и Пермскому краю
description_main: >
    ТурОбоз - Экскурсии по Перми и Пермскому краю,
    экскурсии для школьников,
    туры выходного дня из Перми
description: >
    ТурОбоз - Экскурсии по Перми и Пермскому краю,
    экскурсии для школьников,
    туры выходного дня из Перми
url: https://www.turoboz.com
unsafe_url: http://www.turoboz.com

email: info@turoboz.com
phones:
 - 8 908 275 70 92
 - 8 342 281 15 25
 - 8 342 268 03 62
vk_group: vk.com/club33948424
forms_url: https://briskforms.com/go/61884eb4d90ed4de433bf106bd0aea9a
company_legal:  Туробоз
copyright_dates: 2013-2017
github_username:  none23
# Build settings
markdown: kramdown

# Custom settings
exclude: ["node_modules",
          "gh-pages",
          "Gemfile",
          "Gemfile.lock",
          "gulpfile.js",
          "generate-images",
          "gulpfile.coffee",
          "package.json",
          "fetch-contentful.js",
          "fetch-contentful.js",
          "fetch-vk.js"]
collections:
  tours:
    output: true
  news:
    output: true
  vk_news:
    output: true
permalink: pretty
gems:
  - jekyll-sitemap
