 - tag: school
   title: для школьников
   url: /tours/school/
   description: ''
   subtags:

   - subtag: 1to3
     title: 1-3 классы
     url: /tours/school/1to3/
     description: ''

   - subtag: 4to6
     title: 4-6 классы
     url: /tours/school/4to6/
     description: ''

   - subtag: 7to8
     title: 7-8 классы
     url: /tours/school/7to8/
     description: ''

   - subtag: 9to11
     title: 9-11 классы
     url: /tours/school/9to11/
     description: ''

 - tag: sacred
   title: по святым местам
   url: /tours/sacred/
   description: ''

 - tag: permregion
   title: по Пермскому краю
   url: /tours/permregion/
   description: ''

 - tag: perm
   title: по Перми
   url: /tours/perm/
   description: ''

 - tag: cooking
   title: кулинария
   url: /tours/cooking/
   description: ''

 - tag: russia
   title: по России
   url: /tours/russia/
   description: ''

 - tag: patriot
   title: патриотические
   url: /tours/patriot/
   description: ''

 - tag: weekend
   title: туры выходного дня
   url: /tours/weekend/
   description: ''

 - tag: holiday
   title: праздничные туры
   url: /tours/holiday/
   description: ''
   subtags:

   - subtag: newyear
     title: Новый год
     url: /tours/holiday/newyear/
     description: ''

   - subtag: maslenitsa
     title: Масленица
     url: /tours/holiday/maslenitsa/
     description: ''

